import type { ProviderMeta, ProviderName } from "@/types/provider";

export const PROVIDER_CATALOG: ProviderMeta[] = [
  {
    name: "anthropic",
    displayName: "Anthropic",
    icon: "Brain",
    color: "#D4A574",
    website: "https://console.anthropic.com",
    models: [
      {
        id: "claude-opus-4-20250514",
        name: "Claude Opus 4",
        provider: "anthropic",
        contextWindow: 200000,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        costTier: "high",
        bestFor: ["complex-reasoning", "code", "analysis"],
      },
      {
        id: "claude-sonnet-4-20250514",
        name: "Claude Sonnet 4",
        provider: "anthropic",
        contextWindow: 200000,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        costTier: "medium",
        bestFor: ["general", "code", "writing"],
      },
      {
        id: "claude-haiku-4-5-20251001",
        name: "Claude Haiku 4.5",
        provider: "anthropic",
        contextWindow: 200000,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        costTier: "low",
        bestFor: ["fast-response", "simple-tasks"],
      },
    ],
  },
  {
    name: "openai",
    displayName: "OpenAI",
    icon: "Sparkles",
    color: "#10A37F",
    website: "https://platform.openai.com",
    models: [
      {
        id: "gpt-4o",
        name: "GPT-4o",
        provider: "openai",
        contextWindow: 128000,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        costTier: "medium",
        bestFor: ["general", "code", "vision"],
      },
      {
        id: "gpt-4o-mini",
        name: "GPT-4o Mini",
        provider: "openai",
        contextWindow: 128000,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        costTier: "low",
        bestFor: ["fast-response", "simple-tasks"],
      },
      {
        id: "o3",
        name: "o3",
        provider: "openai",
        contextWindow: 200000,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        costTier: "high",
        bestFor: ["complex-reasoning", "math", "code"],
      },
    ],
  },
  {
    name: "google",
    displayName: "Google AI",
    icon: "Gem",
    color: "#4285F4",
    website: "https://aistudio.google.com",
    models: [
      {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro",
        provider: "google",
        contextWindow: 1000000,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        costTier: "medium",
        bestFor: ["long-context", "multimodal", "code"],
      },
      {
        id: "gemini-2.5-flash",
        name: "Gemini 2.5 Flash",
        provider: "google",
        contextWindow: 1000000,
        supportsTools: true,
        supportsVision: true,
        supportsStreaming: true,
        costTier: "low",
        bestFor: ["fast-response", "long-context"],
      },
    ],
  },
  {
    name: "groq",
    displayName: "Groq",
    icon: "Zap",
    color: "#F55036",
    website: "https://console.groq.com",
    models: [
      {
        id: "llama-3.3-70b-versatile",
        name: "Llama 3.3 70B",
        provider: "groq",
        contextWindow: 131072,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        costTier: "low",
        bestFor: ["fast-response", "general"],
      },
      {
        id: "mixtral-8x7b-32768",
        name: "Mixtral 8x7B",
        provider: "groq",
        contextWindow: 32768,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        costTier: "free",
        bestFor: ["fast-response", "simple-tasks"],
      },
    ],
  },
  {
    name: "fireworks",
    displayName: "Fireworks AI",
    icon: "Flame",
    color: "#FF6B35",
    website: "https://fireworks.ai",
    models: [
      {
        id: "accounts/fireworks/models/llama-v3p3-70b-instruct",
        name: "Llama 3.3 70B",
        provider: "fireworks",
        contextWindow: 131072,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        costTier: "low",
        bestFor: ["general", "code"],
      },
    ],
  },
  {
    name: "mistral",
    displayName: "Mistral AI",
    icon: "Wind",
    color: "#FF7000",
    website: "https://console.mistral.ai",
    models: [
      {
        id: "mistral-large-latest",
        name: "Mistral Large",
        provider: "mistral",
        contextWindow: 128000,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        costTier: "medium",
        bestFor: ["general", "code", "multilingual"],
      },
      {
        id: "codestral-latest",
        name: "Codestral",
        provider: "mistral",
        contextWindow: 32000,
        supportsTools: false,
        supportsVision: false,
        supportsStreaming: true,
        costTier: "low",
        bestFor: ["code"],
      },
    ],
  },
  {
    name: "baseten",
    displayName: "Kimi K2.5 (Baseten)",
    icon: "Box",
    color: "#2563EB",
    website: "https://baseten.co",
    models: [
      {
        id: "moonshotai/Kimi-K2",
        name: "Kimi K2",
        provider: "baseten",
        contextWindow: 131072,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        costTier: "low",
        bestFor: ["complex-reasoning", "code", "general"],
      },
      {
        id: "moonshotai/Kimi-K2.5",
        name: "Kimi K2.5",
        provider: "baseten",
        contextWindow: 131072,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        costTier: "low",
        bestFor: ["complex-reasoning", "code", "general"],
      },
    ],
  },
  {
    name: "perplexity",
    displayName: "Perplexity",
    icon: "Globe",
    color: "#1FB8CD",
    website: "https://docs.perplexity.ai",
    models: [
      {
        id: "sonar-pro",
        name: "Sonar Pro",
        provider: "perplexity",
        contextWindow: 200000,
        supportsTools: false,
        supportsVision: false,
        supportsStreaming: true,
        costTier: "medium",
        bestFor: ["research", "web-search"],
      },
    ],
  },
  {
    name: "together",
    displayName: "Together AI",
    icon: "Users",
    color: "#0EA5E9",
    website: "https://together.ai",
    models: [
      {
        id: "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo",
        name: "Llama 3.1 405B",
        provider: "together",
        contextWindow: 130000,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        costTier: "medium",
        bestFor: ["complex-reasoning", "general"],
      },
    ],
  },
  {
    name: "cohere",
    displayName: "Cohere",
    icon: "MessageSquare",
    color: "#39594D",
    website: "https://dashboard.cohere.ai",
    models: [
      {
        id: "command-r-plus",
        name: "Command R+",
        provider: "cohere",
        contextWindow: 128000,
        supportsTools: true,
        supportsVision: false,
        supportsStreaming: true,
        costTier: "medium",
        bestFor: ["rag", "enterprise", "multilingual"],
      },
    ],
  },
];

export function getProviderMeta(
  name: ProviderName
): ProviderMeta | undefined {
  return PROVIDER_CATALOG.find((p) => p.name === name);
}

export function getDefaultModel(name: ProviderName): string {
  const meta = getProviderMeta(name);
  return meta?.models[0]?.id ?? "";
}
